import Image from 'next/image';
//images
import profileImage from "../public/b.png";
import firstcard from "../public/rocket-white.png";
import webimage from "../public/design.png";
import image1 from "../public/a.jpg";

import { motion } from "framer-motion";

import { Inter } from 'next/font/google';
import Head from "next/head";

//icons
import { BsGithub, BsLinkedin, BsYoutube } from "react-icons/bs";
import { BsFillCloudMoonFill } from "react-icons/bs";
import useColorMode from '@/hooks/useColorMode';
import { animate } from 'framer-motion/dom';


//hook



export default function Home() {

  //function

  const [colorMode, setColorMode] = useColorMode();



  return (

    <div className='dark:bg-black'>
      <Head>
        <title>A</title>
        <meta name='description' content='Generated by create next app' />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;800&display=swap');
        </style>
      </Head>

      <main className='min-h-screen px-10 font-poppins bg-gradient-radial from-green-500 md:px-20 lg:px-40 '>

        {/*nav and hero*/}

        <section>
          {/*nav*/}
          <nav className='flex justify-between py-10'>
            <h1 className=' text-xm md:text-xl dark:text-white'>
              Developed by M.SATHSARA
            </h1>
            <ul className='flex items-center '>
              {/*icon*/}
              <button onClick={() => setColorMode(colorMode === 'light' ? 'dark' : 'light')}>
                <li >

                  <BsFillCloudMoonFill

                    className='mx-5 text-xl cursor-pointer lg:text-xl lg:mx-10 dark:text-white'
                  />

                </li>
              </button>

              <li>
                <a
                  className='px-4 py-2 text-black border-none bg-gradient-to-bl from-green-500 rounded-3xl lg:text-lg dark:text-white'

                  href="https://drive.google.com/file/d/1q9sqQfS7t56Qqw7CM-PVosJW4q0UUYuO/view?usp=sharing"
                  download={"Resume"}
                >Resume</a>
              </li>
            </ul>
          </nav>

          {/*hero*/}
          <div className='py-10 text-center '>
            <h1 className='text-5xl font-bold text-green-500 md:text-6xl lg:text-7xl lg:mb-4'>
              Mithila Sathsara
            </h1>
            <h2 className='py-4 text-2xl font-bold md:text-4xl lg:text-5xl dark:text-white'>
              Undergraduate FullStack Software Engineer
            </h2>
            <p className='max-w-xl py-4 mx-auto text-sm leading-6 text-gray-600 md:text-lg dark:text-gray-200'>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti similique quam vero commodi voluptatum praesentium totam quia deserunt. Enim cum itaque voluptas omnis non sequi nostrum, fuga corporis cupiditate quo?</p>
          </div>


          <div className='flex justify-center gap-16 text-5xl text-gray-500 ' >
            <motion.a
              whileHover={{ scale: 1.1 }}

              href=""> <BsGithub /> </motion.a>
            <motion.a
              whileHover={{ scale: 1.1 }} href=""><BsLinkedin /> </motion.a>
            <motion.a
              whileHover={{ scale: 1.1 }}
              href=""><BsYoutube /> </motion.a>
          </div>

          {/*profile*/}
          <motion.div
            whileHover={{ scale: 1.1 }}
            initial={{ opacity: 1, scale: 1.2 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7 }}
          >
            <div className='relative p-5 m-auto mt-20 rounded-full bg-gradient-to-b from-green-500 w-80 h-80'>
              <Image src={profileImage} alt="" />
            </div>
          </motion.div>


        </section>

        {/*service*/}
        <section>
          <div>
            <h2 className='py-2 text-5xl font-bold opacity-60'>Services </h2>
            <p className='py-4 text-sm leading-6 text-gray-600 dark:text-gray-200'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique eius quo praesentium tenetur, tempore illum eaque iste iusto culpa quas nobis! Nesciunt laborum reprehenderit non! Incidunt dolorum ipsum perspiciatis modi.</p>
          </div>
          {/*service cards*/}


          <div className='gap-10 mx-auto md:flex lg:flex'
          >
            <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.7, }}

          >
            <div className='p-5 my-10 text-center border-4 shadow-sm bg-gradient-to-b from-green-500 rounded-xl border-gray-300/100 '>
              <Image
                src={firstcard} alt='design image web'
                width={500} height={100}
                className='inline' />
              <h2 className='text-2xl font-bold'>
                WEB DESIGNING
              </h2>
              <p className='py-2 text-sm leading-5 text-gray-600 dark:text-gray-200'>
               Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius, earum. Velit quod, expedita totam inventore, nemo dolorem nihil, laborum officia debitis rem eaque porro. Porro commodi culpa fuga numquam similique!
              </p>
            </div>

          </motion.div>
          


          <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.7, }}

          >
            <div className='p-5 my-10 text-center border-4 shadow-sm bg-gradient-to-b from-green-500 rounded-xl border-gray-300/100 '>
              <Image
                src={firstcard} alt='design image web'
                width={500} height={100}
                className='inline' />
              <h2 className='text-2xl font-bold'>
                WEB DESIGNING
              </h2>
              <p className='py-2 text-sm leading-5 text-gray-600 dark:text-gray-200'>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius, earum. Velit quod, expedita totam inventore, nemo dolorem nihil, laborum officia debitis rem eaque porro. Porro commodi culpa fuga numquam similique!
              </p>
            </div>

          </motion.div>
         <motion.div
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.7, }}

          >
            <div className='p-5 my-10 text-center border-4 shadow-sm bg-gradient-to-b from-green-500 rounded-xl border-gray-300/100 '>
              <Image
                src={firstcard} alt='design image web'
                width={500} height={100}
                className='inline' />
              <h2 className='text-2xl font-bold'>
                WEB DESIGNING
              </h2>
              <p className='py-2 text-sm leading-5 text-gray-600 dark:text-gray-200'>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius, earum. Velit quod, expedita totam inventore, nemo dolorem nihil, laborum officia debitis rem eaque porro. Porro commodi culpa fuga numquam similique!
              </p>
            </div>

          </motion.div></div>

          
            
            
          
        </section>

        {/*my works*/}
        <section>
          <h2 className='py-10 text-5xl font-bold opacity-60'>MY WORK</h2>

          <p className='py-2 text-sm leading-5 text-gray-600 dark:text-gray-200'>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius, earum. Velit quod, expedita totam inventore, nemo dolorem nihil, laborum officia debitis rem eaque porro. Porro commodi culpa fuga numquam similique!
          </p>
          {/*images*/}
          <div className='flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap'
          >

            <div className='flex-1 basis-1/3'>
              <motion.div
                whileHover={{ scale: 1.2, }}
                whileTap={{ scale: 0.8, rotate: 20 }}
              >
                <Image
                  src={image1}
                  alt='image01'
                  className='object-cover rounded-xl ' />
              </motion.div></div>

            <div className='flex-1 basis-1/3'>
              <motion.div
                whileHover={{ scale: 1.2, }}
                whileTap={{ scale: 0.8, rotate: -20 }}
              >
                <Image
                  src={image1}
                  alt='image01'
                  className='object-cover rounded-xl ' />
              </motion.div></div>

            <div className='flex-1 basis-1/3'>
              <motion.div
                whileHover={{ scale: 1.2, }}
                whileTap={{ scale: 0.8, rotate: 20 }}
              >
                <Image
                  src={image1}
                  alt='image01'
                  className='object-cover rounded-xl ' />
              </motion.div></div>
            <div className='flex-1 basis-1/3'>
              <motion.div
                whileHover={{ scale: 1.2, }}
                whileTap={{ scale: 0.8, rotate: -20 }}
              >
                <Image
                  src={image1}
                  alt='image01'
                  className='object-cover rounded-xl ' />
              </motion.div></div>

            <div className='flex-1 basis-1/3'>
              <motion.div
                whileHover={{ scale: 1.2, }}
                whileTap={{ scale: 0.8, rotate: 20 }}
              >
                <Image
                  src={image1}
                  alt='image01'
                  className='object-cover rounded-xl ' />
              </motion.div></div>


            <div className='flex-1 basis-1/3'>
              <motion.div
                whileHover={{ scale: 1.2, }}
                whileTap={{ scale: 0.8, rotate: -20 }}
              >
                <Image
                  src={image1}
                  alt='image01'
                  className='object-cover rounded-xl ' />
              </motion.div></div>






          </div>


        </section>

        {/*footer*/}
        <footer className='flex flex-col items-center justify-center gap-5 py-10 text-sm border-t-2 border-black opacity-80 lg:flex-row lg:items-center dark:text-gray-200 dark:border-white'>
          <div className=''>
            <h3 className='mb-2 text-base '>Contact Me</h3>
            <p className='opacity-50 '>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Temporibus ad exercitationem ab, ut qui accusantium eos nemo officia eveniet beatae cupiditate nam tenetur consectetur repellat eligendi impedit sunt, aliquam nobis?</p>


          </div>
          <div>
            <div className='flex justify-center gap-16 text-5xl text-gray-500 dark:text-gray-200' >
              <a href=""> <BsGithub /> </a>
              <a href=""><BsLinkedin /> </a>
              <a href=""><BsYoutube /> </a>
            </div>
          </div></footer>

      </main>
    </div>

  )


}
